remote_theme: danbraj/falcon-jekyll-theme

title: Keyboard Race "Wyścig na klawiaturze" Multiplayer
description: Aplikacja do ćwiczenia szybkiego pisania na klawiaturze z elementami rywalizacji
lang: pl

kramdown: 
  toc_levels: '2,3'

# Custom
nav:
  - title: Author
    url: https://github.com/danbraj